services:
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_DNS=redis://redis:6379

  publisher:
    build: ./app
    depends_on:
      - ${REDIS_SERVICE}
    environment:
      - REDIS_DNS=redis://redis:6379
    command: ["node", "publisher.js"]

  subscriber1:
    build: ./app
    depends_on:
      - ${REDIS_SERVICE}
    environment:
      - REDIS_DNS=redis://redis:6379
    command: ["node", "subscriber1.js"]

  subscriber2:
    build: ./app
    depends_on:
      - ${REDIS_SERVICE}
    environment:
      - REDIS_DNS=redis://redis:6379
    command: ["node", "subscriber1.js"]
