services:
  redis:
    image: redis
    ports:
      - 6379

  mongo:
    image: mongo
    restart: no # ??
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: no # ??
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: ${MONGO_DSN}
      ME_CONFIG_BASICAUTH: false # ??

    depends_on:
      - mongo
   
  app:
    image: node
    working_dir: /app
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: [npm, start]

volumes:
  node_modules:
  mongo_data:
