services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  app:
    image: node
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - redis
    command: [node, index.js]

volumes:
  node_modules:
