services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  app:
    image: node
    working_dir: /app
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: [node, index.js]

volumes:
  node_modules:
  redis_data:
