services:
  redis:
    image: redis:latest
    ports:
      - 6379

  publisher:
    # build: ./app
    image: node:18
    env_file:
      - .env
    working_dir: /app
    volumes:
      - "./app:/app"
      - ./app/node_modules:/app/node_modules
    depends_on:
      - redis
    command: ["node", "publisher.js"]

  subscriber1:
    # build: ./app
    image: node:18
    env_file:
      - .env
    working_dir: /app
    volumes:
      - "./app:/app"
      - ./app/node_modules:/app/node_modules
    depends_on:
      - redis
    command: ["node", "subscriber1.js"]

  subscriber2:
    # build: ./app
    image: node:18
    env_file:
      - .env
    working_dir: /app
    volumes:
      - "./app:/app"
      - ./app/node_modules:/app/node_modules
    depends_on:
      - redis
    command: ["node", "subscriber1.js"]

volumes:
  node_modules:
