services:
  redis:
    image: redis
    ports:
      - 6379
   
  app:
    image: node
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: [node, index.js]

volumes:
  node_modules:
